### PR TITLE
`e.target` -› `e.currentTarget` in `_eventOpenPointer()`

### LINKED ISSUE #100: InnerHTML in open modal link.
When I create a "a href" element to open the modal with innerHTML like a <span> and I click on the link to open the modal it throws a JS error:

> fr-dialogmodal.js?1480591233158:6 Uncaught TypeError: Cannot read property 'querySelectorAll' of null(…)

Link example:

`<a href="#" class="js--modal-open" data-video-id="12345678" aria-controls="modal-video">
        <span> Link title </span>
    </a>`

Is it not possible to have a open-modal link with "span" or other elements inside? I've debugged the JS a bit and it looks like it's going wrong on line 121: let button = e.target;

When clicking on a link with inner elements the target is the "span" instead of the "a href", so it can't find the aria-controls.

Is there a fix for this?

### PR DESCRIPTION
**Pull request by davidhund**
Using `e.currentTarget` instead of `e.target` fixes issues with modal link containing sub-elements.
Resolves #100

### CODE REVIEW

**Review by adamduncan — APPROVED** [review]
Looks good, thanks David! 👍

**Comment by davidhund** [comment]
Woop woop! 🚀 

PS: Just now I realized the exact same thing [c|sh]ould be done for Tabs: at https://github.com/frend/frend.co/blob/develop/_components/tabs/tabs.js#L134

```
_showTab(e.currentTarget);
```

(This allows e.g. a `span` in the `a.fr-tabs__tab`)

**Comment by davidhund** [comment]
@adamduncan — could you please publish this latest `fr-dialogmodal v1.0.3` to npm if you have not already? And do you want me to PR the similar fix for `fr-tabs`?

**Comment by adamduncan** [comment]
Thanks @davidhund! Tried publishing 1.0.3 but getting 'previously published' npm errors. I might need to bump to 1.0.4 instead.

Appreciate the tabs PR as well, thank you. Thought we did a `currentTarget` sweep last year, but seems we've missed a couple. I'll get your contributions wrapped up shortly.

**Pull request merged**
