### PR TITLE
Accordion: e.currentTarget instead of e.target

### PR DESCRIPTION
**Pull request by gunzip**
This will enable having subelements inside accordion trigger / header.

ie. 

```
    <h2 class="Accordion-header js-fr-accordion__header fr-accordion__header" id="accordion-header-1" >
        <span class="Accordion-link">Open 1</span>
    </h2>

```

### CODE REVIEW

**Comment by thomasdigby** [comment]
This looks good, can you add the compiled version and we'll merge it in.

**Comment by adamduncan** [comment]
Nice, thanks. Hey, worth merging the gh-pages master into this fork first, as there were [changes to tabs](https://github.com/frend/frend.co/commit/4cb70b925f4ca219254505fc4c36acd8509e887e) yesterday. A re-commit of _tabs.js_ and _/dist/frtabs.min.js_, patch bump to v1.0.6 in the [package.json](https://github.com/frend/frend.co/blob/gh-pages/_components/tabs/package.json) and an entry in the [changelog](https://github.com/frend/frend.co/blob/gh-pages/_components/tabs/CHANGELOG.md) should do the trick.

(I'll add some these points in the Contributing notes, as it's not clear at the moment, sorry.)

**Comment by adamduncan** [comment]
Hey, sorry @gunzip - I had Tabs on the mind, and you're clearly working on Accordion. Thanks for the Changelog/package.json bump. Merging...

**Comment by adamduncan** [comment]
Thanks for your input. Published to npm @1.0.6

**Pull request merged**
