### PR TITLE
Allow innerHTML in Tab links by using e.currentTarget in _eventTabCli…

### PR DESCRIPTION
**Pull request by davidhund**
Using `e.currentTarger` in `_eventTabClick (e)` allows innerHTML in Tabs: e.g. a `span` in the links. Without `currentTarget`, clicking the span (in the link) will break the script. Ref #102

### CODE REVIEW

**Review by adamduncan — CHANGES_REQUESTED** [review]
Code and versioning's great, thanks. Minor tweak needed on the version number in changelog and we'll roll this in and republish. Cheers 👍

**Comment by davidhund** [comment]
Oops. Bumped the version to `1.0.6` in CHANGELOG now.. ✋

**Comment by thomasdigby** [comment]
@adamduncan Just need to run an `npm publish` 👍

**Comment by adamduncan** [comment]
Cheers guys. 

fr-tabs at `1.0.6` https://www.npmjs.com/package/fr-tabs
fr-dialogmodal at `1.0.4` https://www.npmjs.com/package/fr-dialogmodal

**Pull request merged**
